In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('커피빈.csv')
df

          Name                           Address           Tel
0     삼성봉은사거리점             서울시 강남구 영동대로 607 1,2층  02-3443-5618
1    코엑스웨스틴서울점   서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드   02-569-3103
2      삼성오크우드점           서울 강남구 테헤란로87길 46 지하 2층  02-3466-8507
3      삼성봉은사로점           서울시 강남구 봉은사로 628 엘슨빌딩1층   02-538-4523
4      도심공항타워점        서울시 강남구 테헤란로87길 36 공항타워 1층  02-2016-5330
..         ...                               ...           ...
208  강동경희대병원앞점         서울특별시 강동구 동남로 885 양지빌딩 1층   02-481-9938
209      새문안로점       서울특별시 종로구 새문안로 91 고려빌딩 1,2층   02-739-5806
210  광화문역1번출구점           서울시 종로구 새문안로5가길 7 1층 일부   02-723-3360
211   성균관대법학관점   서울시 종로구 성균관로 25-2 성균관대학교 법학관 B2   02-740-1958
212    경희궁의아침점  서울시 종로구 새문안로3길 23 경희궁아침상가4단지105외   02-730-8896

[213 rows x 3 columns]

In [21]:
import requests

# 주소(문자열)를 입력받아 카카오 API를 통해 위치 정보를 반환하는 함수
def get_location(address):
    # 카카오 로컬 API 주소 (주소 검색용 endpoint)
    url = 'https://dapi.kakao.com/v2/local/search/address.json?query=' + address
    
    # API 인증키 (KakaoAK + 본인 REST API 키)
    headers = {
        'Authorization': 'KakaoAK dae86cabcb069c73392d01772a2ad095'
    }
    
    # requests.get()을 사용해 API 요청 -> 결과를 JSON으로 변환
    res = requests.get(url, headers=headers).json()

    # 좌표만 추출하고 싶다면:
    if res.get("documents"):
        x = res["documents"][0]["x"]  # 경도
        y = res["documents"][0]["y"]  # 위도
        print("위도:", y, "경도:", x)
    else: #검색이 실패했을 때 x = np.nan, y = np.nan으로 채우면 > 이후 데이터프레임으로 정리할 때 “빈값”으로 표시
        x = np.nan
        y = np.nan
    
    # 변환된 JSON 데이터를 반환
    return x, y

In [22]:
x, y = get_location('서울시 강남구 영동대로 607')
x, y

위도: 37.5145473024381 경도: 127.059486615422

('127.059486615422', '37.5145473024381')

In [24]:
df.head(2)

        Name                          Address           Tel
0   삼성봉은사거리점            서울시 강남구 영동대로 607 1,2층  02-3443-5618
1  코엑스웨스틴서울점  서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드   02-569-3103

In [27]:
for i in df.index:
    address = df.loc[i, 'Address']
    x, y = get_location(address)
    df.loc[i, 'x'] = x
    df.loc[i, 'y'] = y

위도: 37.5129534255276 경도: 127.057115600619
위도: 37.5109823973192 경도: 127.058205573267
위도: 37.5146694627537 경도: 127.064164448221

/var/folders/6h/ftjqrp5d10s0c81fzrz29p0m0000gn/T/ipykernel_34777/7372762.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '127.057115600619' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'x'] = x
/var/folders/6h/ftjqrp5d10s0c81fzrz29p0m0000gn/T/ipykernel_34777/7372762.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '37.5129534255276' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'y'] = y

위도: 37.5102336492314 경도: 127.058597240146
위도: 37.510356849269 경도: 127.061023782931
위도: 37.5096322564759 경도: 127.059443354483
위도: 37.5091916919873 경도: 127.06080691987
위도: 37.5107115918746 경도: 127.054150521266
위도: 37.5070611225729 경도: 127.058776738588
위도: 37.5070873831686 경도: 127.062895193334
위도: 37.50589366006 경도: 127.058292440311
위도: 37.5199060766075 경도: 127.050036555762
위도: 37.5061948324582 경도: 127.052402933477
위도: 37.5045993053356 경도: 127.056186481052
위도: 37.5047428849251 경도: 127.053159553826
위도: 37.5056868654944 경도: 127.047899800263
위도: 37.5034040395308 경도: 127.050586603895
위도: 37.5102810924204 경도: 127.042972144359
위도: 37.503773975836 경도: 127.048914400159
위도: 37.5252547717564 경도: 127.047232410937
위도: 37.5244894827177 경도: 127.044387474036
위도: 37.5418967410602 경도: 126.949787848373
위도: 37.4796070667241 경도: 126.952183895644
위도: 37.5769954696057 경도: 126.972649439494
위도: 37.4434253308098 경도: 127.140977607565
위도: 37.5218090317976 경도: 126.929697406323
위도: 37.5242915298626 경도: 126.929338616058
위도: 37.5197460148873 경도: 126.928066576601
위도: 37.5248882861767 경도: 126.927297465564
위도: 37.5251775245928 경도: 126.924876706923
위도: 37.522516139033 경도: 126.924586046016
위도: 37.5307295655332 경도: 126.924843194287
위도: 37.5568275244158 경도: 126.92508838544
위도: 37.5554722456428 경도: 126.923266632289
위도: 37.4110208490997 경도: 127.126360491293
위도: 37.4095029491435 경도: 127.125978531405
위도: 37.5172332566615 경도: 126.903715993779
위도: 36.3509886552386 경도: 127.388960470639
위도: 37.6390955501842 경도: 127.025725359083
위도: 37.4849270383011 경도: 126.896538036905
위도: 37.5454041231797 경도: 127.223940331575
위도: 37.5081230677129 경도: 126.888212953215
위도: 37.5196469645582 경도: 126.88904246102
위도: 37.6538310278932 경도: 127.06017787506
위도: 37.6004493355977 경도: 126.921096166394
위도: 37.3853420421398 경도: 127.12523654354
위도: 37.478720573213 경도: 126.886476789522
위도: 37.3781334075052 경도: 127.112312363818
위도: 37.3935078942772 경도: 126.959414289663
위도: 37.5281783139269 경도: 126.875771989415
위도: 37.5797159011058 경도: 126.892773992481
위도: 37.5797159011058 경도: 126.892773992481
위도: 37.3707082053063 경도: 127.105603334255
위도: 37.582468718569 경도: 126.887937496441
위도: 37.3724051471608 경도: 126.947202895332
위도: 37.5548546834697 경도: 126.851250232655
위도: 37.4171034624346 경도: 126.880947375247
위도: 37.5114162901687 경도: 127.081689148468
위도: 37.4966225187716 경도: 127.055233195315
위도: 37.5100538600899 경도: 127.035957481795
위도: 37.5237561531657 경도: 127.037083772824
위도: 37.5263370842465 경도: 127.038182970834
위도: 37.50102236437 경도: 127.039885329906
위도: 37.5078448024619 경도: 127.034665821539
위도: 37.5070324421316 경도: 127.034714418284
위도: 37.502349282282 경도: 127.036521514294
위도: 37.5159610912838 경도: 127.029536928342
위도: 37.500619211163 경도: 127.034897822252
위도: 37.4985735366506 경도: 127.03648868939
위도: 37.4990862800943 경도: 127.034141792509
위도: 37.4922389145982 경도: 127.041675092178
위도: 37.524421297629 경도: 127.027426608456
위도: 37.3585078307294 경도: 126.930982279358
위도: 37.5629234842805 경도: 126.826076887806
위도: 37.5608751008131 경도: 126.824695969186
위도: 37.4614946950643 경도: 126.813963062169
위도: 35.8699830814753 경도: 128.59879306028
위도: 37.30508998386 경도: 127.002952238108
위도: 37.6317396610579 경도: 126.832991977195
위도: 37.65408246185 경도: 127.273684824487
위도: 37.4866835002109 경도: 126.782823051713
위도: 37.2906667925637 경도: 127.050518820725
위도: 37.2959770000514 경도: 126.974164012539
위도: 37.7448754366902 경도: 127.095257911166
위도: 37.2688010652736 경도: 127.026459525531
위도: 37.294066695953 경도: 127.202128029885
위도: 37.2649449442455 경도: 127.0326839743
위도: 37.2903638439839 경도: 127.200511081391
위도: 37.2655920786365 경도: 127.000179930083
위도: 35.1781697810343 경도: 128.14576837039
위도: 37.6567152545134 경도: 126.773131388502
위도: 37.6558964094856 경도: 126.772038816453
위도: 37.2462246621025 경도: 127.057572127932
위도: 35.2396668440149 경도: 128.654408692296
위도: 35.2234911053458 경도: 128.680810708184
위도: 37.5055116110689 경도: 127.02605222215
위도: 37.4961482913142 경도: 127.032169064933
위도: 37.4989136957534 경도: 127.029260610601
위도: 37.5045343907375 경도: 127.025594068116
위도: 37.5020858941495 경도: 127.026069579038
위도: 37.5001117846329 경도: 127.027290827849
위도: 37.5068517133248 경도: 127.022823344866
위도: 37.5023574434123 경도: 127.024880498727
위도: 37.5318069076157 경도: 127.027000294801
위도: 37.5119461613615 경도: 127.020431538347
위도: 37.4985502394657 경도: 127.025735420451
위도: 37.4956734817567 경도: 127.028208465188
위도: 37.4855733712043 경도: 127.045052231494
위도: 37.4966333557707 경도: 127.026914460572
위도: 37.4967437284397 경도: 127.025703589132
위도: 37.4974340616184 경도: 127.024516764632
위도: 37.4912870511791 경도: 127.03026231978
위도: 37.5165777895252 경도: 127.101225932288
위도: 37.5070691238449 경도: 127.101553183969
위도: 37.535725176732 경도: 127.095692162256
위도: 35.2240810071698 경도: 129.008755219018
위도: 37.6645540981816 경도: 126.754526582068
위도: 35.1854467005759 경도: 129.082381897171
위도: 35.1563071015735 경도: 129.058041866196
위도: 35.1688178394069 경도: 129.129523260187
위도: 35.1678106760758 경도: 129.132817784816
위도: 35.1067181869781 경도: 129.036529466282
위도: 35.098981097777 경도: 129.035685630449
위도: 37.2296433007505 경도: 127.188439781762
위도: 37.2058406007355 경도: 127.074679321062
위도: 37.2048484896364 경도: 127.069281504509
위도: 37.6365009365146 경도: 126.677577628872
위도: 37.7294215154692 경도: 126.736860627485
위도: 37.3786608661181 경도: 126.662841516858
위도: 37.3802255186684 경도: 126.656372166201
위도: 37.7063244875731 경도: 126.686213843644
위도: 37.4827666361943 경도: 127.034949554107
위도: 37.53985699394 경도: 127.09489656845
위도: 37.5145543838088 경도: 127.10796656942
위도: 37.4987321235919 경도: 127.015601806503
위도: 37.5003183328671 경도: 127.011825492621
위도: 37.4956330957501 경도: 127.013538414144
위도: 37.5169302452841 경도: 127.112781230361
위도: 37.4887766507842 경도: 127.104115178497
위도: 37.1593983647558 경도: 126.813524514918
위도: 33.5128730968875 경도: 126.527560680131
위도: 33.4844445262988 경도: 126.534540530554
위도: 37.1593983647558 경도: 126.813524514918
위도: 37.1593983647558 경도: 126.813524514918
위도: 33.4780630755235 경도: 126.363585353938
위도: 37.4855373251844 경도: 127.015576900888
위도: 37.5441340657514 경도: 127.10293064906
위도: 37.486696128715 경도: 127.010531864513
위도: 37.4690084600597 경도: 127.04013984355
위도: 37.5348144623725 경도: 126.998481292627
위도: 37.4934207705586 경도: 126.491489796733
위도: 37.4692488244219 경도: 126.43320918812
위도: 37.458350712273 경도: 126.427699293474
위도: 37.0004682235819 경도: 127.11150165951
위도: 37.5285655568387 경도: 126.993107501389
위도: 37.524564226881 경도: 127.128015153134
위도: 37.570948129697 경도: 127.070501006018
위도: 37.4860552797801 경도: 127.12100938212
위도: 37.4836465628118 경도: 127.122198444997
위도: 37.4796870553794 경도: 127.124979804141
위도: 37.4957101117888 경도: 126.985532367698
위도: 37.8665963452691 경도: 127.720054731926
위도: 37.345730271733 경도: 127.927649555629
위도: 37.5614599246316 경도: 126.985707093498
위도: 37.5288173852679 경도: 126.966653789116
위도: 37.5297718014452 경도: 126.964741503485
위도: 37.5873771473625 경도: 127.026248862202
위도: 37.5651546444578 경도: 126.985010733916
위도: 37.5543029383069 경도: 126.974048614143
위도: 37.5698794886241 경도: 126.988409831075
위도: 37.555503632236 경도: 126.973751343837
위도: 37.5643288057316 경도: 126.98132044403
위도: 37.5678035976862 경도: 126.984507517226
위도: 37.5814020979301 경도: 127.003706808109
위도: 37.5664918220199 경도: 126.981865819602
위도: 37.5664918220199 경도: 126.981865819602
위도: 37.56991129156 경도: 126.985169386018
위도: 37.3233830428989 경도: 127.981662850501
위도: 37.5730079037521 경도: 126.987334399767
위도: 37.5623085377513 경도: 126.975593964647
위도: 37.5670466069498 경도: 126.979375711608
위도: 37.5716808092144 경도: 126.983530268891
위도: 37.5602669008102 경도: 126.972035325682
위도: 37.5835220981147 경도: 127.001154914843
위도: 37.5690748736876 경도: 126.977592007714
위도: 37.5684232177354 경도: 126.97825653257
위도: 37.5964485466639 경도: 127.084792605442
위도: 37.5697855426617 경도: 126.978860937689
위도: 37.5718747898899 경도: 126.979481465774
위도: 37.5526535932606 경도: 127.155975988269
위도: 37.5704876038354 경도: 126.974761002545
위도: 37.5727711995017 경도: 126.974038245085
위도: 37.5872284082508 경도: 126.993115116294
위도: 37.5726308227784 경도: 126.972440824541

In [29]:
df.isnull().sum()
df.dropna(inplace=True)

In [30]:
df.head()

,Name,Address,Tel,x,y
1,코엑스웨스틴서울점,서울시 강남구 봉은사로 524 코엑스 인터컨티넨탈아케이드,02-569-3103,127.057115600619,37.5129534255276
2,삼성오크우드점,서울 강남구 테헤란로87길 46 지하 2층,02-3466-8507,127.058205573267,37.5109823973192
3,삼성봉은사로점,서울시 강남구 봉은사로 628 엘슨빌딩1층,02-538-4523,127.064164448221,37.5146694627537
4,도심공항타워점,서울시 강남구 테헤란로87길 36 공항타워 1층,02-2016-5330,127.058597240146,37.5102336492314
5,트레이드타워점,서울시 강남구 영동대로 511 트레이드타워 지하1층,02-803-9994,127.061023782931,37.510356849269

In [48]:
df.to_csv('커피빈맵.csv')

In [49]:
address = '마포구'
filt = df['Address'].str.contains(address)
store = df[filt]
store

,Name,Address,Tel,x,y
24,마포경찰공제회점,"서울시 마포구 마포대로 78 (도화동 566), 경찰공제회 자람빌딩 1층",02-704-6591,126.949787848373,37.5418967410602
39,홍대역8번출구점,서울시 마포구 양화로18안길 7 2층,02-338-9463,126.92508838544,37.5568275244158
40,홍대역점,서울시 마포구 홍익로 6길 26,02-333-4278,126.923266632289,37.5554722456428
57,상암SBS프리즘타워점,서울 마포구 상암산로 82 SBS 프리즘 타워 1층 로비,02-562-9605,126.892773992481,37.5797159011058
58,상암SBS미디어센터점,서울시 마포구 상암산로 82 SBS프리즘타워 1층,02-2039-9027,126.892773992481,37.5797159011058
60,상암한국지역정보개발원점,서울시 마포구 성암로301 KLID한국지역정보개발원 1층,02-376-9162,126.887937496441,37.582468718569

In [58]:
import folium 

def get_map(address):
    filt = df['Address'].str.contains(address, na=False)  # 주소 검색
    store = df[filt]

    if len(store.index) == 0:  # 검색 결과 없을 때
        print('검색 주소 없음')
        return

    first = store.iloc[0]      # 첫 번째 검색 결과 선택
    lon = first['x']           # 경도
    lat = first['y']           # 위도

    map = folium.Map(location=[lat, lon], zoom_start=15)  # 지도 생성

    # ✅ 모든 검색 결과에 대해 마커 추가
    for _, row in store.iterrows():
        folium.Marker(
            location=[row['y'], row['x']], 
            icon=folium.Icon(color='red', icon='star')
        ).add_to(map)

    map.save(f'{address}.html')  # HTML로 저장

# 실행 예시
get_map('마포구')