In [1]:
import pandas as pd

In [2]:
#class, age, fare별 생존률 구하는데 쓰임
train = pd.read_csv('train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
train.shape  #행, 열 개수

(891, 12)

In [5]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
train.groupby('Survived').size()  #train.value_counts('Survived')

Survived
0    549
1    342
dtype: int64

In [7]:
train.value_counts('Survived', normalize=True)  #비율***

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

'성별'별 생존율

In [8]:
total = train.groupby('Sex').size().to_frame('전체인원')
total

        전체인원
Sex
female   314
male     577

In [9]:
filt = train['Survived'] == 1
survived = train[filt]
survived = survived.groupby('Sex').size().to_frame('생존인원')
survived

        생존인원
Sex
female   233
male     109

In [10]:
gender = total.join(survived)  #total.merge(survived, on='Sex')
gender['생존율'] = gender['생존인원']/gender['전체인원']
gender  #여자가 생존율이 더 높다

        전체인원  생존인원       생존율
Sex
female   314   233  0.742038
male     577   109  0.188908

'티켓 클래스'별 생존율

In [11]:
total = train.groupby('Pclass').size().to_frame('전체인원')
total

        전체인원
Pclass
1        216
2        184
3        491

In [12]:
filt = train['Survived'] == 1
survived = train[filt]
pclass = survived.groupby('Pclass').size().to_frame('생존인원')
pclass

        생존인원
Pclass
1        136
2         87
3        119

In [13]:
pclass = total.join(pclass)
pclass['생존율'] = pclass['생존인원']/pclass['전체인원']
pclass  #class가 좋을 수록 생존율이 높다

        전체인원  생존인원       생존율
Pclass
1        216   136  0.629630
2        184    87  0.472826
3        491   119  0.242363

'연령대'별 생존율

In [14]:
train['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [15]:
filt = train['Age'] == train['Age'].min()
train[filt]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C

In [16]:
ages = []
min = int(train['Age'].min())
max = int(train['Age'].max())

for age in range(min, max+1, 10):  #min에서 max+1까지 10씩 증가
    ran = f'{age}이상 ~ {age+10}미만'

    filt = (train['Age'] >= age) & (train['Age'] < age+10)
    count = train[filt]['Age'].count()  #인원수

    ages.append({'나이': ran, '인원수':count})

ages

[{'나이': '0이상 ~ 10미만', '인원수': np.int64(62)},
 {'나이': '10이상 ~ 20미만', '인원수': np.int64(102)},
 {'나이': '20이상 ~ 30미만', '인원수': np.int64(220)},
 {'나이': '30이상 ~ 40미만', '인원수': np.int64(167)},
 {'나이': '40이상 ~ 50미만', '인원수': np.int64(89)},
 {'나이': '50이상 ~ 60미만', '인원수': np.int64(48)},
 {'나이': '60이상 ~ 70미만', '인원수': np.int64(19)},
 {'나이': '70이상 ~ 80미만', '인원수': np.int64(6)},
 {'나이': '80이상 ~ 90미만', '인원수': np.int64(1)}]

In [ ]:
# 탑승항구(Embarked)별 전체 인원, 생존 인원, 생존율

In [ ]:
group = train.groupby(['Embarked', 'Pclass']).size().to_frame()
c = group['C']
s = group['S']
q = group['Q']
df = pd.DataFrame([c, s, q], index=['C', 'S', 'Q'])
df.index.name = '항구'
df

Pclass    1    2    3
C        85   17   66
S       127  164  353
Q         2    3   72

In [ ]:
group=train.groupby(['Embarked', 'pc;dd'                               d','Pclass']),size